const fs = require('fs');
const path = require('path');

const enPath = path.join(__dirname, 'messages', 'en.json');
const dePath = path.join(__dirname, 'messages', 'de.json');

const enData = JSON.parse(fs.readFileSync(enPath, 'utf8'));
const deData = JSON.parse(fs.readFileSync(dePath, 'utf8'));

const enInventory = {
  ...enData.pharmacy.inventory,
  "ledger": "Product Ledger",
  "newSku": "Add Product",
  "noResults": "No products match your criteria.",
  "colProduct": "Product",
  "colCategory": "Category",
  "colStrength": "Strength",
  "colStock": "Stock Level",
  "colStatus": "Status",
  "colActions": "Actions",
  "lastRestock": "Restocked: {date}",
  "threshold": "Threshold",
  "statusCritical": "Critical",
  "statusLow": "Low Stock",
  "statusInStock": "In Stock",
  "orderOpen": "Order open: {qty} {unit} ({date})",
  "receive": "Receive",
  "reorder": "Reorder",
  "manage": "Manage",
  "history": "History",
  "showing": "Showing {count} items",
  "newTitle": "Add New Product",
  "sku": "SKU",
  "name": "Product Name",
  "category": "Category",
  "categoryFlower": "Flower",
  "categoryOil": "Oil",
  "categoryExtract": "Extract",
  "categoryCapsule": "Capsule",
  "thc": "THC %",
  "cbd": "CBD %",
  "stockLevel": "Current Stock",
  "unit": "Unit",
  "unitPieces": "pcs",
  "safetyThreshold": "Safety Threshold",
  "create": "Create",
  "cancel": "Cancel",
  "editTitle": "Manage {name}",
  "stockNote": "To adjust stock levels accurately, use Reorder/Receive or the History view.",
  "archive": "Archive Product",
  "save": "Save Changes",
  "reorderTitle": "Reorder {name}",
  "reorderText": "Enter the quantity you want to reorder.",
  "qty": "Quantity ({unit})",
  "placeOrder": "Place Order",
  "receiveTitle": "Receive {name}",
  "receiveText": "Confirm the received quantity to add to stock.",
  "receivedQty": "Received ({unit})",
  "cancelOrder": "Cancel Order",
  "confirmReceive": "Receive Stock",
  "archiveTitle": "Archive Product",
  "archiveText": "Are you sure you want to archive {name}? It will no longer appear in the active inventory, but its history will be retained.",
  "confirmArchive": "Yes, Archive",
  "historyTitle": "History: {name}",
  "logTransaction": "Log Manual Transaction",
  "historyEmpty": "No transactions found.",
  "inbound": "INBOUND",
  "outflow": "OUTFLOW",
  "batch": "Batch",
  "batchOptional": "Batch (Optional)",
  "patient": "Patient",
  "logTitle": "Log Transaction for {name}",
  "transactionType": "Transaction Type",
  "noteOptional": "Note (Optional)",
  "totalSkus": "Total SKUs",
  "lowStock": "Low Stock",
  "critical": "Critical",
  "pendingOrders": "Pending Orders",
  "attention": "Attention Needed",
  "immediate": "Action Required",
  "exportCsv": "Export CSV",
  "alertTitle": "Critical Low Stock",
  "alertText": "{name} has fallen to critically low levels (Threshold: {threshold} {unit}). Please reorder immediately.",
  "alertMulti": "And {count} other critical alerts..."
};

const deInventory = {
  ...deData.pharmacy.inventory,
  "ledger": "Produkthistorie",
  "newSku": "Produkt hinzufügen",
  "noResults": "Keine Produkte gefunden.",
  "colProduct": "Produkt",
  "colCategory": "Kategorie",
  "colStrength": "Stärke",
  "colStock": "Lagerbestand",
  "colStatus": "Status",
  "colActions": "Aktionen",
  "lastRestock": "Letzter Eingang: {date}",
  "threshold": "Mindestmenge",
  "statusCritical": "Kritisch",
  "statusLow": "Niedrig",
  "statusInStock": "Auf Lager",
  "orderOpen": "Offene Bestellung: {qty} {unit} ({date})",
  "receive": "Wareneingang",
  "reorder": "Nachbestellen",
  "manage": "Verwalten",
  "history": "Historie",
  "showing": "Zeige {count} Artikel",
  "newTitle": "Neues Produkt hinzufügen",
  "sku": "SKU",
  "name": "Produktname",
  "category": "Kategorie",
  "categoryFlower": "Blüten",
  "categoryOil": "Öl",
  "categoryExtract": "Extrakt",
  "categoryCapsule": "Kapsel",
  "thc": "THC %",
  "cbd": "CBD %",
  "stockLevel": "Aktueller Bestand",
  "unit": "Einheit",
  "unitPieces": "Stk.",
  "safetyThreshold": "Sicherheitsbestand",
  "create": "Erstellen",
  "cancel": "Abbrechen",
  "editTitle": "{name} verwalten",
  "stockNote": "Um Bestände korrekt anzupassen, nutzen Sie bitte Nachbestellen/Wareneingang oder die Historie.",
  "archive": "Produkt archivieren",
  "save": "Änderungen speichern",
  "reorderTitle": "{name} nachbestellen",
  "reorderText": "Geben Sie die Bestellmenge ein.",
  "qty": "Menge ({unit})",
  "placeOrder": "Bestellen",
  "receiveTitle": "Wareneingang {name}",
  "receiveText": "Bestätigen Sie die eingegangene Menge.",
  "receivedQty": "Eingang ({unit})",
  "cancelOrder": "Bestellung stornieren",
  "confirmReceive": "Bestand buchen",
  "archiveTitle": "Produkt archivieren",
  "archiveText": "Möchten Sie {name} wirklich archivieren? Es wird nicht mehr im aktiven Bestand geführt, aber die Historie bleibt erhalten.",
  "confirmArchive": "Ja, archivieren",
  "historyTitle": "Historie: {name}",
  "logTransaction": "Manuelle Buchung",
  "historyEmpty": "Keine Transaktionen gefunden.",
  "inbound": "ZUGANG",
  "outflow": "ABGANG",
  "batch": "Charge",
  "batchOptional": "Charge (Optional)",
  "patient": "Patient",
  "logTitle": "Buchung für {name}",
  "transactionType": "Buchungsart",
  "noteOptional": "Notiz (Optional)",
  "totalSkus": "Gesamt SKUs",
  "lowStock": "Niedriger Bestand",
  "critical": "Kritisch",
  "pendingOrders": "Offene Bestellungen",
  "attention": "Achtung",
  "immediate": "Sofort handeln",
  "exportCsv": "CSV Export",
  "alertTitle": "Kritischer Lagerbestand",
  "alertText": "Der Bestand von {name} ist kritisch niedrig (Mindestmenge: {threshold} {unit}). Bitte umgehend nachbestellen.",
  "alertMulti": "Und {count} weitere kritische Warnungen..."
};

enData.pharmacy.inventory = enInventory;
deData.pharmacy.inventory = deInventory;

fs.writeFileSync(enPath, JSON.stringify(enData, null, 2));
fs.writeFileSync(dePath, JSON.stringify(deData, null, 2));
console.log("Translations patched successfully!");
